captainVersion: 4

services:

  $$cap_appname:
    image: ghcr.io/voltdatalab/xarta-entrypoint
    environment:
      PROJECT_NAME: srv-captain--$$cap_appname
    volumes:
      # Do not use underscore
      - $$cap_appname-entrypoint-caddy-data:/data
      - $$cap_appname-entrypoint-caddy-config:/config

  $$cap_appname-next:
    image: ghcr.io/voltdatalab/xarta
    environment:
      # Required for get-settings
      INTERNAL_GHOST_URL: http://srv-captain--$$cap_appname
      # TODO: Set automatically via setup-helper
      # For now, these will have to be manually set by the user
      # GHOST_ADMIN_API_KEY: ${GHOST_ADMIN_API_KEY}
      # GHOST_CONTENT_API_KEY: ${GHOST_CONTENT_API_KEY}
      # Required for set language
      NEXT_INTERNAL_ROOT_URL: http://srv-captain--$$cap_appname
      # Used to connect to Xarta Postgres DB
      # Required for the database scripts
      XARTA_DB_HOST: srv-captain--$$cap_appname-xarta-db
      XARTA_DB_USER: $$cap_xarta_db_user
      XARTA_DB_PASSWORD: $$cap_xarta_db_password
      # Variables for Next.js public and server
      # TODO: Allow both HTTP and HTTPS
      PUBLIC_ROOT_URL: $$cap_public_url
    volumes:
      - $$cap_appname-setup-helper-data:/.setup-helper      
    caproverExtra:
      notExposeAsWebApp: true      

  $$cap_appname-ghost:
    image: ghost:5.118.0
    environment:
        url: $$cap_public_url
        NODE_ENV: production
        # Disable 2FA so that staff logins don't depend on emails
        # TODO: Consider reenabling
        security__staffDeviceVerification: false
        database__client: mysql
        database__connection__host: srv-captain--$$cap_appname-ghost-db
        # TODO: Add custom user option?
        database__connection__user: root
        database__connection__password: $$cap_ghost_db_password
        database__connection__database: ghost
    volumes:
      - $$cap_appname-xarta-ghost-data:/var/lib/ghost/content
    # Fixes errors when ghost cannot connect to mysql database on init 
    restart: unless-stopped
    depends_on:
      $$cap_appname-ghost-db:
        condition: service_healthy
    caproverExtra:
      notExposeAsWebApp: true        

  $$cap_appname-ghost-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $$cap_ghost_db_password
    volumes:
      - $$cap_appname-xarta-ghost-db-data:/var/lib/mysql
    # Required, otherwise ghost will fail during startup
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
    caproverExtra:
      notExposeAsWebApp: true      

  $$cap_appname-xarta-db:
    image: postgres:17
    environment:
      POSTGRES_USER: $$cap_xarta_db_user
      POSTGRES_PASSWORD: $$cap_xarta_db_password
      POSTGRES_DB: "xarta"
    volumes:
      - $$cap_appname-xarta-db-data:/var/lib/postgresql/data
    caproverExtra:
      notExposeAsWebApp: true      

  $$cap_appname-setup-helper:
    image: ghcr.io/voltdatalab/xarta-setup
    environment:
      CADDY_CONTAINER_NAME: "srv-captain--$$cap_appname"
      PROJECT_NAME: srv-captain--$$cap_appname
      GHOST_DB_PASSWORD: $$cap_ghost_db_password
      PUBLIC_URL: $$cap_public_url
    # Force caprover behavior on setup helper
    # TODO: Bug in caprover? Entrypoint vanishes when command exists
    command: ["/app/setup-entrypoint.sh", "--cap-rover", "--site-title", "$$cap_site_title" , "--name", "$$cap_admin_name", "--email", "$$cap_admin_email", "--password", "$$cap_admin_password" ]
    volumes:
      - $$cap_appname-setup-helper-data:/.setup-helper
    caproverExtra:
      notExposeAsWebApp: true

caproverOneClickApp:
  variables:

    - id: $$cap_public_url
      label: Public URL
      description: |
        Enter the public URL for your app, which must use HTTPS. 
        
        **Important: You must change the default string!** Either:

        - **Use the default app domain:** **replace only the uppercase string `APP_NAME_HERE` with the same value as above**.

        - **Use a custom domain:** simply replace the entire value with the domain.

      defaultValue: https://APP_NAME_HERE.$$cap_root_domain
      validRegex: '/^https:\/\//'


    - id: '$$cap_site_title'
      label: Site Title
      description: Site title. Defaults to Xarta, but you may also use your brand's name, for example.
      defaultValue: Xarta
      validRegex: '/.{1,}/'

    - id: '$$cap_admin_name'
      label: Ghost Admin Full name.
      description: Full name for the Ghost admin account.
      defaultValue: Admin User
      validRegex: '/.{1,}/'

    - id: '$$cap_admin_email'
      label: Ghost Admin Email
      description: Login email for the Ghost admin account. You can use yours, if preferred.
      defaultValue: admin-$$cap_gen_random_hex(6)@example.com
      validRegex: '/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/'

    - id: '$$cap_admin_password'
      label: Ghost Admin Initial Password
      description: Initial Login password for the Ghost admin account. **Important:** You should change this password after setup is complete.
      defaultValue: $$cap_gen_random_hex(16)
      validRegex: '/.{10,}/'    

    - id: '$$cap_ghost_db_password'
      label: Ghost Database Password
      description: Password for the Ghost MySQL database.
      defaultValue: $$cap_gen_random_hex(16)
      validRegex: '/.{8,}/'
      
    - id: '$$cap_xarta_db_user'
      label: Xarta Database User
      description: Username for the Xarta PostgreSQL database.
      defaultValue: 'xarta-db-user'
      validRegex: '/^[a-zA-Z0-9_\-]+$/'
      
    - id: '$$cap_xarta_db_password'
      label: Xarta Database Password
      description: Password for the Xarta PostgreSQL database.
      defaultValue: $$cap_gen_random_hex(16)
      validRegex: '/.{8,}/'

  instructions:
    start: |-
      Xarta is a card creation and publishing platform built on top of Ghost CMS.
      
      This one-click app will install:
      - Xarta Next.js frontend
      - Ghost CMS backend
      - MySQL database for Ghost
      - PostgreSQL database for Xarta
      - Caddy reverse proxy
      - Setup helper container
      
      After installation, you'll need to complete the Xarta setup process by accessing the setup-helper container 
      and follow its instructions.
      
    end: |-
      Xarta has been successfully deployed!

      -----------------------------------------

      Please follow the instructions below to finish configuring your Xarta:

      **IMPORTANT: Open the links below in a new browser tab to avoid navigating away from this page!**

      [https://captain.$$cap_root_domain/#/apps/details/$$cap_appname](https://captain.$$cap_root_domain/#/apps/details/$$cap_appname)
      - In app `$$cap_appname`:
        - If you're using a custom domain:
          - Add the custom domain to the list, then click `Connect New Domain`.
          - Point your DNS records to the IP address of the server running CapRover.
        - Activate `Enable HTTPS` for the desired domain;
        - Enable option `Force HTTPS by redirecting all HTTP traffic to HTTPS`;
        - Save and restart.
      
      - **Important**: Access the Ghost admin panel at:
      [$$cap_public_url/ghost/#/settings/staff]($$cap_public_url/ghost/#/settings/staff)
        - Login with your credentials:
          - Email: `$$cap_admin_email`
          - Password: `$$cap_admin_password`
          - **Please change your password as soon as possible!**
            - Click your username (`$$cap_admin_name`) > View Profile > Password > Change

      [https://captain.$$cap_root_domain/#/apps/details/$$cap_appname-setup-helper](https://captain.$$cap_root_domain/#/apps/details/$$cap_appname-setup-helper)
      - Optional: Delete `$$cap_appname-setup-helper` after setup is complete:
          - Click `Deployment` and analyze logs at `View App Logs`/`Hide App Logs`.
          - Ensure `🎉 Xarta Setup Complete!` shows in the logs.
          - Go back to `HTTP Settings` and click `Delete App`.
            - Optional: deselect volume `$$cap_appname-setup-helper-data`.
            - **Note:** volume `$$cap_appname-setup-helper-data` will not be removed as it is being used by containers.

      - Finally, access your Xarta instance at:
      [$$cap_public_url/xarta]($$cap_public_url/xarta)
      
      -----------------------------------------
      
  displayName: Xarta
  isOfficial: false
  description: Xarta is a card creation and publishing platform built on top of Ghost CMS.
  documentation: This configuration is based on the official Xarta docker-compose setup from https://github.com/voltdatalab/xarta
