captainVersion: 4

services:

  $$cap_appname:
    image: ghcr.io/voltdatalab/xarta-reverse-proxy
    environment:
      PROJECT_NAME: srv-captain--$$cap_appname
    volumes:
      - $$cap_appname-entrypoint_caddy_data:/data
      - $$cap_appname-entrypoint_caddy_config:/config

  $$cap_appname-next:
    image: ghcr.io/voltdatalab/xarta
    environment:
      # Required for get-settings
      INTERNAL_GHOST_URL: http://srv-captain--$$cap_appname
      # TODO: Set automatically via setup-helper
      # GHOST_ADMIN_API_KEY: ${GHOST_ADMIN_API_KEY}
      # GHOST_CONTENT_API_KEY: ${GHOST_CONTENT_API_KEY}
      # Required for set language
      NEXT_INTERNAL_ROOT_URL: http://srv-captain--$$cap_appname
      # Used to connect to Xarta Postgres DB
      # Required for the database scripts
      XARTA_DB_HOST: srv-captain--$$cap_appname-xarta-db
      XARTA_DB_USER: $$cap_xarta_db_user
      XARTA_DB_PASSWORD: $$cap_xarta_db_password
      # Variables for Next.js public and server
      PUBLIC_ROOT_URL: $$cap_appname.$$cap_root_domain

  $$cap_appname-ghost:
    image: ghost:5.118.0
    environment:
        - url=$$cap_appname.$$cap_root_domain
        - NODE_ENV=production
        # Disable 2FA so that staff logins don't depend on emails
        # TODO: Consider reenabling
        - security__staffDeviceVerification=false
        - database__client=mysql
        - database__connection__host=srv-captain--$$cap_appname-ghost-db
        # TODO: Add custom user option?
        - database__connection__user=root
        - database__connection__password=$$cap_ghost_db_password
        - database__connection__database=ghost
    volumes:
      - $$cap_appname-xarta_ghost_data:/var/lib/ghost/content
    # Fixes errors when ghost cannot connect to mysql database on init 
    restart: unless-stopped
    depends_on:
      $$cap_appname-ghost-db:
        condition: service_healthy    

  $$cap_appname-ghost-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $$cap_ghost_db_password
    volumes:
      - $$cap_appname-xarta_ghost_db_data:/var/lib/mysql
    # Required, otherwise ghost will fail during startup
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  $$cap_appname-xarta-db:
    image: postgres:17
    environment:
      POSTGRES_USER: $$cap_xarta_db_user
      POSTGRES_PASSWORD: $$cap_xarta_db_password
      POSTGRES_DB: "xarta"
    volumes:
      - $$cap_appname-xarta_db_data:/var/lib/postgresql/data

  $$cap_appname-setup-helper:
    image: ghcr.io/voltdatalab/xarta-setup
    environment:
      CADDY_CONTAINER_NAME: "srv-captain--$$cap_appname"
      PROJECT_NAME: srv-captain--$$cap_appname
      GHOST_DB_PASSWORD: $$cap_ghost_db_password
      PUBLIC_URL: $$cap_appname.$$cap_root_domain
    profiles: [setup]
    # Force caprover behavior on setup helper
    command: --caprover
    # Keeps the container running as an interactive terminal
    # tty: true
    # Used to allow providing input to attach
    # stdin_open: true
    depends_on:
      $$cap_appname-ghost:
        condition: service_started
        restart: false