import { GhostTag } from "@/components/types/GhostTag";



export const tagsExample: GhostTag[] = [
    {
        id: "1",
        name: "Technology",
        slug: "technology",
        description: "All about the latest in tech.",
        feature_image: "https://example.com/images/tech.png",
        visibility: "public",
        meta_title: "Technology",
        meta_description: "Explore the latest in technology.",
        url: "https://example.com/tags/technology",
        og_image: "https://example.com/images/tech-og.png",
        og_title: "Technology News",
        og_description: "Latest updates in technology.",
        twitter_image: "https://example.com/images/tech-twitter.png",
        twitter_title: "Technology Updates",
        twitter_description: "Catch up with the latest tech trends.",
        codeinjection_head: null,
        codeinjection_foot: null,
        canonical_url: "https://example.com/tags/technology",
        accent_color: "#ff5733",
    },
    {
        id: "2",
        name: "Health",
        slug: "health",
        description: "Health tips and news.",
        feature_image: "https://example.com/images/health.png",
        visibility: "public",
        meta_title: "Health",
        meta_description: "Stay healthy with our tips.",
        url: "https://example.com/tags/health",
        og_image: "https://example.com/images/health-og.png",
        og_title: "Health and Wellness",
        og_description: "All about health and wellness.",
        twitter_image: "https://example.com/images/health-twitter.png",
        twitter_title: "Health Tips",
        twitter_description: "Learn how to stay healthy.",
        codeinjection_head: null,
        codeinjection_foot: null,
        canonical_url: "https://example.com/tags/health",
        accent_color: "#33ff57",
    },
    {
        id: "3",
        name: "Business",
        slug: "business",
        description: "Insights and news from the business world.",
        feature_image: "https://example.com/images/business.png",
        visibility: "private",
        meta_title: "Business",
        meta_description: "Get the latest business insights.",
        url: "https://example.com/tags/business",
        og_image: "https://example.com/images/business-og.png",
        og_title: "Business News",
        og_description: "Latest updates in the business world.",
        twitter_image: "https://example.com/images/business-twitter.png",
        twitter_title: "Business Insights",
        twitter_description: "Stay informed with business news.",
        codeinjection_head: null,
        codeinjection_foot: null,
        canonical_url: "https://example.com/tags/business",
        accent_color: "#5733ff",
    },
];
