import { tagsExample } from "@/components/functional/EditarCard/tagsExample";
import { GhostPost } from "@/components/types/GhostPost";

// AI-generated
export const postsExample: GhostPost[] = [
    {
        "id": "1",
        "title": "Understanding JavaScript Closures",
        "slug": "understanding-javascript-closures",
        "html": "<p>JavaScript closures are a fundamental concept in the language...</p>",
        "feature_image": "https://example.com/images/js-closures.jpg",
        "excerpt": "A deep dive into the concept of closures in JavaScript.",
        "custom_excerpt": "Learn about closures in JavaScript with practical examples.",
        "visibility": "public",
        "status": "published",
        "published_at": "2024-03-15T10:00:00Z",
        "updated_at": "2024-03-20T14:30:00Z",
        "created_at": "2024-03-10T09:00:00Z",
        "meta_title": "JavaScript Closures Explained",
        "meta_description": "An article that explains closures in JavaScript.",
        "og_image": "https://example.com/images/js-closures-og.jpg",
        "og_title": "Understanding JavaScript Closures",
        "og_description": "Explore the concept of closures in JavaScript.",
        "twitter_image": "https://example.com/images/js-closures-twitter.jpg",
        "twitter_title": "Understanding JavaScript Closures",
        "twitter_description": "A comprehensive guide to JavaScript closures.",
        "codeinjection_head": "<style>.highlight { background-color: yellow; }</style>",
        "codeinjection_foot": "<script>console.log('Page loaded');</script>",
        "canonical_url": "https://example.com/javascript-closures",
        "tags": [],
        "primary_tag": tagsExample[0],
        "primary_author": {
            "id": "201",
            "name": "Jane Doe",
            "slug": "jane-doe",
            "profile_image": "https://example.com/authors/jane-doe.jpg",
            "bio": "Jane is a software engineer with a passion for teaching.",
            "website": "https://jane.doe.dev",
            "location": "San Francisco, CA",
            "facebook": "https://facebook.com/janedoe",
            "twitter": "https://twitter.com/janedoe",
            "url": "https://example.com/author/jane-doe",
            cover_image: '',
            meta_title: '',
            meta_description: ''
        },
        uuid: 'abcdef',
        comment_id: 'asdf',
        feature_image_alt: 'asdf',
        feature_image_caption: 'asdf',
        featured: false,
        custom_template: null,
        authors: [],
        url: 'asdf',
        reading_time: 1234
    },
    {
        "slug": "introduction-to-react-hooks",
        "id": "3",
        "uuid": "123e4567-e89b-12d3-a456-426614174000",
        "title": "Introduction to React Hooks",
        "html": "<p>React Hooks provide a powerful way to use state and other React features without writing a class...</p>",
        "comment_id": "3",
        "feature_image": "https://example.com/images/react-hooks.jpg",
        "feature_image_alt": "React Hooks Illustration",
        "feature_image_caption": "An illustration representing React Hooks in action.",
        "featured": true,
        "meta_title": "Learn React Hooks",
        "meta_description": "A comprehensive guide to React Hooks, covering useState, useEffect, and more.",
        "created_at": "2024-04-01T10:00:00Z",
        "updated_at": "2024-04-05T15:00:00Z",
        "published_at": "2024-04-02T08:00:00Z",
        "custom_excerpt": "Explore the power of React Hooks and how they can simplify your React components.",
        "codeinjection_head": "<style>.highlight { background-color: yellow; }</style>",
        "codeinjection_foot": "<script>console.log('React Hooks article loaded');</script>",
        "og_image": "https://example.com/images/react-hooks-og.jpg",
        "og_title": "Introduction to React Hooks",
        "og_description": "Discover the key concepts of React Hooks in this in-depth article.",
        "twitter_image": "https://example.com/images/react-hooks-twitter.jpg",
        "twitter_title": "Understanding React Hooks",
        "twitter_description": "A deep dive into React Hooks and their usage in modern React development.",
        "custom_template": null,
        "canonical_url": "https://example.com/introduction-to-react-hooks",
        "authors": [
            {
                "id": "301",
                "name": "Alice Johnson",
                "slug": "alice-johnson",
                "profile_image": "https://example.com/authors/alice-johnson.jpg",
                "bio": "Alice is a front-end developer with a passion for teaching React.",
                "website": "https://alice.dev",
                "location": "Austin, TX",
                "facebook": "https://facebook.com/alicejohnson",
                "twitter": "https://twitter.com/alicejohnson",
                "url": "https://example.com/author/alice-johnson",
                cover_image: null,
                meta_title: null,
                meta_description: null
            }
        ],
        "tags": [
            {
                "id": "105",
                "name": "React",
                "slug": "react",
                "description": "Articles about React, a JavaScript library for building user interfaces.",
                "feature_image": null,
                "visibility": "public",
                "meta_title": "React Articles",
                "meta_description": "Stay updated with the latest articles about React.",
                "url": "https://example.com/tag/react",
                "og_image": null,
                "og_title": null,
                "og_description": null,
                "twitter_image": null,
                "twitter_title": null,
                "twitter_description": null,
                "codeinjection_head": null,
                "codeinjection_foot": null,
                "canonical_url": null,
                "accent_color": null
            },
            {
                "id": "106",
                "name": "JavaScript",
                "slug": "javascript",
                "description": "JavaScript is the programming language of the web.",
                "feature_image": null,
                "visibility": "public",
                "meta_title": null,
                "meta_description": null,
                "url": "https://example.com/tag/javascript",
                "og_image": null,
                "og_title": null,
                "og_description": null,
                "twitter_image": null,
                "twitter_title": null,
                "twitter_description": null,
                "codeinjection_head": null,
                "codeinjection_foot": null,
                "canonical_url": null,
                "accent_color": null
            }
        ],
        "primary_author": {
            "id": "301",
            "name": "Alice Johnson",
            "slug": "alice-johnson",
            "profile_image": "https://example.com/authors/alice-johnson.jpg",
            "bio": "Alice is a front-end developer with a passion for teaching React.",
            "website": "https://alice.dev",
            "location": "Austin, TX",
            "facebook": "https://facebook.com/alicejohnson",
            "twitter": "https://twitter.com/alicejohnson",
            "url": "https://example.com/author/alice-johnson",
            cover_image: null,
            meta_title: null,
            meta_description: null
        },
        "primary_tag": {
            "id": "105",
            "name": "React",
            "slug": "react",
            "description": "Articles about React, a JavaScript library for building user interfaces.",
            "feature_image": null,
            "visibility": "public",
            "meta_title": "React Articles",
            "meta_description": "Stay updated with the latest articles about React.",
            "url": "https://example.com/tag/react",
            "og_image": null,
            "og_title": null,
            "og_description": null,
            "twitter_image": null,
            "twitter_title": null,
            "twitter_description": null,
            "codeinjection_head": null,
            "codeinjection_foot": null,
            "canonical_url": null,
            "accent_color": null
        },
        "url": "https://example.com/introduction-to-react-hooks",
        "excerpt": "A quick overview of what React Hooks are and how to use them in your React applications.",
        "visibility": "public",
        "reading_time": 7,
        "status": "published"
    }
];
