name: Build and Push Docker Images

on:
  # This will run when PRs are merged into main
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # GitHub repository owner
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Next.js image
      - name: Extract metadata for Next.js image
        id: meta-next
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/xarta
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag
            latest

      - name: Build and push Next.js image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.next
          push: true
          tags: ${{ steps.meta-next.outputs.tags }}
          labels: ${{ steps.meta-next.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Setup CLI image
      - name: Extract metadata for Setup CLI image
        id: meta-setup
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/xarta-setup
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag
            latest

      - name: Build and push Setup CLI image
        uses: docker/build-push-action@v5
        with:
          context: ./tools/setup
          file: ./tools/setup/Dockerfile
          push: true
          tags: ${{ steps.meta-setup.outputs.tags }}
          labels: ${{ steps.meta-setup.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
